apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: hello-nginx
          image: sahil867/msil-demo-repo:IMAGE_TAG
          ports:
            - containerPort: 80
