apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-dev
  template:
    metadata:
      labels:
        app: demo-app-dev
    spec:
      containers:
        - name: demo-app-dev
          image: sahil867/msil-demo-repo:IMAGE_TAG
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "DEV"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodeport
  namespace: dev
spec:
  type: NodePort
  selector:
    app: demo-app-dev
  ports:
    - name: http
      protocol: TCP
      port: 80          # Service port
      targetPort: 3000  # Container port
      nodePort: 30080   # NodePort (optional but fixed)
