apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: hello-nginx
          image: sahil867/msil-demo-repo:IMAGE_TAG
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional (range 30000â€“32767)
