apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpass
  MYSQL_DATABASE: demo_db
  MYSQL_USER: demo_user
  MYSQL_PASSWORD: demo_pass
