apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Optional (range 30000â€“32767)
