apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx
        image: bom.ocir.io/oscemea006/demo-app-repo:IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        # REQUIRED FOR HPA
        resources:
          requests:
            cpu: "900m"
            memory: "950Mi"
          limits:
            cpu: "950m"
            memory: "950Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
  namespace: prod
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30081

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hello-nginx-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-nginx
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
