apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-prod
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app-prod
  template:
    metadata:
      labels:
        app: demo-app-prod
    spec:
      containers:
        - name: demo-app-prod
          image: sahil867/msil-demo-repo:IMAGE_TAG
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              value: "PROD"


---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodeport-prod
  namespace: prod
spec:
  type: NodePort
  selector:
    app: demo-app-prod
  ports:
    - name: http
      protocol: TCP
      port: 80          # Service port
      targetPort: 3000  # Container port
